# Generated by Django 3.0.3 on 2020-05-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='signup_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
