# Generated by Django 3.0.3 on 2020-05-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_userinfo_signup_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('discipline', models.CharField(max_length=64)),
                ('organizer', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('limit', models.IntegerField()),
                ('deadline', models.DateField()),
                ('num_of_seeded', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('logo', models.ImageField(upload_to='logos')),
                ('tournaments', models.ManyToManyField(to='tournaments.Tournament')),
            ],
        ),
    ]
