# Generated by Django 3.0.3 on 2020-05-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_localization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='tournaments',
        ),
        migrations.CreateModel(
            name='Sponsoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Sponsor')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament')),
            ],
            options={
                'unique_together': {('tournament', 'sponsor')},
            },
        ),
    ]
