# Generated by Django 3.0.3 on 2020-05-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_auto_20200506_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='num_of_registered',
            field=models.IntegerField(default=0),
        ),
    ]
