# Generated by Django 3.0.3 on 2020-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_match_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='seed',
            field=models.IntegerField(default=-1),
        ),
    ]
