# Generated by Django 3.0.3 on 2020-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_participation_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
