# Generated by Django 3.0.3 on 2020-05-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_auto_20200506_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.IntegerField(default=1),
        ),
    ]
