# Generated by Django 3.0.3 on 2020-05-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_auto_20200506_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user1_seed',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='match',
            name='user2_seed',
            field=models.IntegerField(default=-1),
        ),
    ]
