# Generated by Django 3.0.3 on 2020-05-07 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0019_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user1_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1_decision', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='user2_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user2_decision', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
