# Generated by Django 3.0.3 on 2020-05-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_auto_20200507_1459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'number')},
        ),
    ]
